language: node_js

node_js:
  - 'node'
  - '12'
  - '10'
  - '8'

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

branches:
  only:
    - master

before_script:
  - npm install --prefix ./

script:
  - npm run test

install:
  - npm uninstall typescript --no-save
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1
